apiVersion: v1
kind: Service
metadata:
    name: "kubernetesdemo-17ae"
    labels:
        app: "kubernetesdemo-17ae"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetesdemo-17ae"