##See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
#
#FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
#WORKDIR /app
#EXPOSE 80
#EXPOSE 443
#
#FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
#WORKDIR /src
#COPY ["CICDWebApiDemo/CICDWebApiDemo.csproj", "CICDWebApiDemo/"]
#RUN dotnet restore "CICDWebApiDemo/CICDWebApiDemo.csproj"
#COPY . .
#WORKDIR "/src/CICDWebApiDemo"
#RUN dotnet build "CICDWebApiDemo.csproj" -c Release -o /app/build
#
#FROM build AS publish
#RUN dotnet publish "CICDWebApiDemo.csproj" -c Release -o /app/publish
#
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/publish .
#
#ENTRYPOINT ["dotnet", "CICDWebApiDemo.dll"]
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
#COPY ["DemoAPIAzure467/DemoAPIAzure467.csproj", "DemoAzureApi/"]
#COPY /DemoAPIAzure467/DemoAPIAzure467.csproj .
COPY CICDWebApiDemo.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "CICDWebApiDemo.dll"]