on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kubernetesdemoregistry01.azurecr.io
        username: ${{ secrets.acr_kubernetesdemoregistry01_username }}
        password: ${{ secrets.acr_kubernetesdemoregistry01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CICDWebApiDemo" -f  "CICDWebApiDemo/Dockerfile" -t kubernetesdemoregistry01.azurecr.io/kubernetesdemo:${{ github.sha }} --label dockerfile-path=CICDWebApiDemo/Dockerfile
        docker push kubernetesdemoregistry01.azurecr.io/kubernetesdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetesdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetesdemoa798 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetesdemoa798`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetesdemoa798
        container-registry-url: kubernetesdemoregistry01.azurecr.io
        container-registry-username: ${{ secrets.acr_kubernetesdemoregistry01_username }}
        container-registry-password: ${{ secrets.acr_kubernetesdemoregistry01_password }}
        secret-name: kubernetesdedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetesdemoa798
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          kubernetesdemoregistry01.azurecr.io/kubernetesdemo:${{ github.sha }}
        imagepullsecrets: |
          kubernetesdedockerauth
