on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akscontainerregistry02.azurecr.io
        username: ${{ secrets.acr_akscontainerregistry02_username }}
        password: ${{ secrets.acr_akscontainerregistry02_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CICDWebApiDemo" -f  "CICDWebApiDemo/Dockerfile" -t akscontainerregistry02.azurecr.io/aksdemo:${{ github.sha }} --label dockerfile-path=CICDWebApiDemo/Dockerfile
        docker push akscontainerregistry02.azurecr.io/aksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksdemoa00c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksdemoa00c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksdemoa00c
        container-registry-url: akscontainerregistry02.azurecr.io
        container-registry-username: ${{ secrets.acr_akscontainerregistry02_username }}
        container-registry-password: ${{ secrets.acr_akscontainerregistry02_password }}
        secret-name: aksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksdemoa00c
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          akscontainerregistry02.azurecr.io/aksdemo:${{ github.sha }}
        imagepullsecrets: |
          aksdemodockerauth
